name: docker-ros

on:
  push:
    branches:
      - main
      - test-ci
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - uses: ika-rwth-aachen/docker-ros@copilot/pass-run-and-dev-image-name
        id: docker-ros
        with:
          platform: amd64
          target: dev,run
          base-image: rwthika/ros2:jazzy
          rmw-implementation: rmw_zenoh_cpp
          command: ros2 launch openads_demo_service openads_demo_service_launch.py
          enable-industrial-ci: true
          label-maintainer: Institute for Automotive Engineering (ika), RWTH Aachen University <opensource@ika.rwth-aachen.de>
          label-authors: Institute for Automotive Engineering (ika), RWTH Aachen University <opensource@ika.rwth-aachen.de>
        env:
          TARGET_CMAKE_ARGS: -DCMAKE_EXPORT_COMPILE_COMMANDS=1
      - run: docker run --rm "${{ steps.docker-ros.outputs.run-image }}" ros2 node list
      - run: docker run --rm "${{ steps.docker-ros.outputs.dev-image }}" ls /docker-ros/ws/src/target
      - run: docker run --rm "${{ steps.docker-ros.outputs.slim-image }}"
